"""create exams and questions tables

Revision ID: fb479a021dfa
Revises: 355f46816f4d
Create Date: 2026-08-19 13:01:32.581801

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fb479a021dfa"
down_revision: Union[str, Sequence[str], None] = "355f46816f4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
